project:
  type: website

website:
  title: "lincolab.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    mainfont: "Atkinson Hyperlegible" 
    css: 
      - styles.css
      - www/css/comfortaa.css
      - www/css/atkinson-hyperlegible.css
    toc: true

editor: visual

